### ISSUE TITLE
Dependencies wipe out existing ones

### ISSUE THREAD

**Issue by lmeyerov** [pyg-team/pyg-lib#196]
### 🐛 Describe the bug

We're installing on a nvidia rapids container (22.12), with carefully selected cuda version (in this case 11.3, where their max is 11.5). Installing pyg-lib via pip does not preserve existing installs. For example, cuda 11.7 gets installed, which would break rapids. I did not see a conda version that might have been more careful.

### Environment

rapids 22.12 ubuntu 20.04  cuda 11.3 container with torch 1.12

**Comment by rusty1s** [comment]
Thanks for reporting. Can you clarify your issues? `pyg-lib` does not have any dependency on CUDA (see [here](https://github.com/pyg-team/pyg-lib/blob/master/setup.py)), so I don't see why `pyg-lib` should not preserve the existing installation.

**Comment by lmeyerov** [comment]
Looking more closely at the trace, it looks `FROM rapids...cu11.3` (largely mamba-based) + `pip install torch 1.12.1` + `pip install pyg-lib ...` + `mamba install pyg` was the issue. The mamba `pyg` step updates to `cu11.7` etc, not the `pyg-lib`. Switching the mamba step to `pip` honors the env, solving the immediate issue.
