### ISSUE TITLE
`test_fused_scatter_reduce` fails w/ latest triton (compilation error)

### ISSUE THREAD

**Issue by puririshi98** [pyg-team/pyg-lib#210]
### 🐛 Describe the bug

the error is most likely caused by an update to triton to commit `d54c04abe2c3e67b2139c68cdbda87b59e8dd01b`

<img width="873" alt="Screen Shot 2023-03-07 at 12 45 08 PM" src="https://user-images.githubusercontent.com/20074092/223548324-5cc6b54f-179b-46f3-9d37-c608ca3ac01d.png">

```
root@4fda8fcd9b9f:/workspace# py.test -s /opt/pyg/pyg-lib/test/ops/test_scatter_reduce.py::test_fused_scatter_reduce -v
/usr/local/lib/python3.8/dist-packages/triton/compiler.py:942: CompilationError
```
full log:
[triton_compile_err.txt](https://github.com/pyg-team/pyg-lib/files/10913812/triton_compile_err.txt)

**Comment by rusty1s** [comment]
I assume that's why one does not test against nightly releases :P Will take a look.

**Comment by rusty1s** [comment]
will be fixed as part of https://github.com/openai/triton/pull/1301/files.

**Comment by puririshi98** [comment]
> I assume that's why one does not test against nightly releases :P Will take a look.

yeah sorry, our pytorch team had to update to the latest triton to fix bugs on their end and then we are forced to use their pytorch base container so it carried over. nonetheless, thnx for investigating :)
