### ISSUE TITLE
Installation fails due to `ERROR: Could not find a version that satisfies the requirement pyg-lib` on macOS

### ISSUE THREAD

**Issue by Mars-Mah3r** [pyg-team/pyg-lib#211]
### 😵 cant install pyg

Everytime i use the command:
`pip install pyg-lib -f https://data.pyg.org/whl/torch-1.13.1+cpu.html`
I get the error message
`ERROR: Could not find a version that satisfies the requirement pyg-lib (from versions: none)
ERROR: No matching distribution found for pyg-lib`

### Environment

* `pyg-lib` version: n/a
* PyTorch version: 1.13.1
* OS: Mac OS Version 13.2.1 
* Python version: 3.10.5
* CUDA/cuDNN version: n/a
* How you installed PyTorch and `pyg-lib` (`conda`, `pip`, source): pip 
* Any other relevant information:

**Comment by rusty1s** [comment]
Yeah, that's because we don't yet provide pre-built M1 wheels, and `pyg-lib` is not yet on PyPi. You can try to run via
```
pip install git+https://github.com/pyg-team/pyg-lib.git

**Comment by Mars-Mah3r** [comment]
> Yeah, that's because we don't yet provide pre-built M1 wheels, and `pyg-lib` is not yet on PyPi. You can try to run via
> 
> ```
> pip install git+https://github.com/pyg-team/pyg-lib.git
> ```

when i try to do that, i get the following error message 

`mars@Mars-MacBook-Pro ~ % pip install git+https://github.com/pyg-team/pyg-lib.git
Collecting git+https://github.com/pyg-team/pyg-lib.git
  Cloning https://github.com/pyg-team/pyg-lib.git to /private/var/folders/gq/qt59drb965v4rlchdht8jmzr0000gn/T/pip-req-build-1t0asuw1
  error: subprocess-exited-with-error
  
  × git version did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git version did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
mars@Mars-MacBook-Pro ~ % `

**Comment by Mars-Mah3r** [comment]
> Yeah, that's because we don't yet provide pre-built M1 wheels, and `pyg-lib` is not yet on PyPi. You can try to run via
> 
> ```
> pip install git+https://github.com/pyg-team/pyg-lib.git
> ```

now i get this error:

```
mars@Mars-MacBook-Pro ~ % pip install git+https://github.com/pyg-team/pyg-lib.git

Collecting git+https://github.com/pyg-team/pyg-lib.git
  Cloning https://github.com/pyg-team/pyg-lib.git to /private/var/folders/gq/qt59drb965v4rlchdht8jmzr0000gn/T/pip-req-build-alw447aw
  Running command git clone --filter=blob:none --quiet https://github.com/pyg-team/pyg-lib.git /private/var/folders/gq/qt59drb965v4rlchdht8jmzr0000gn/T/pip-req-build-alw447aw
  Resolved https://github.com/pyg-team/pyg-lib.git to commit 76ef32a22cb43e9f1bb66a0298acfa13f48ef23e
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Installing collected packages: pyg-lib
  DEPRECATION: pyg-lib is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pyg-lib ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pyg-lib did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-3.10
      creating build/lib.macosx-10.9-universal2-3.10/pyg_lib
      copying pyg_lib/home.py -> build/lib.macosx-10.9-universal2-3.10/pyg_lib
      copying pyg_lib/__init__.py -> build/lib.macosx-10.9-universal2-3.10/pyg_lib
      copying pyg_lib/testing.py -> build/lib.macosx-10.9-universal2-3.10/pyg_lib
      copying pyg_lib/_triton.py -> build/lib.macosx-10.9-universal2-3.10/pyg_lib
      creating build/lib.macosx-10.9-universal2-3.10/pyg_lib/sampler
      copying pyg_lib/sampler/__init__.py -> build/lib.macosx-10.9-universal2-3.10/pyg_lib/sampler
      creating build/lib.macosx-10.9-universal2-3.10/pyg_lib/ops
      copying pyg_lib/ops/scatter_reduce.py -> build/lib.macosx-10.9-universal2-3.10/pyg_lib/ops
      copying pyg_lib/ops/__init__.py -> build/lib.macosx-10.9-universal2-3.10/pyg_lib/ops
      running build_ext
      /private/var/folders/gq/qt59drb965v4rlchdht8jmzr0000gn/T/pip-req-build-alw447aw/setup.py:77: UserWarning: Building times of 'pyg-lib' can be heavily improved by installing 'ninja': `pip install ninja`
        warnings.warn("Building times of 'pyg-lib' can be heavily improved"
      error: [Errno 2] No such file or directory: 'cmake'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyg-lib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
mars@Mars-MacBook-Pro ~ % --use-pep517
zsh: command not found: --use-pep517
mars@Mars-MacBook-Pro ~ % 
```

**Comment by rusty1s** [comment]
You need to install PyTorch beforehand before being able to install `pyg-lib` from source.

**Comment by Mars-Mah3r** [comment]
> You need to install PyTorch beforehand before being able to install `pyg-lib` from source.

Pytorch is installed

**Comment by rusty1s** [comment]
I am a bit confused. We currently don't use `pyproject.toml` for `pyg-lib`. Not totally sure why it complains about it TBH.

**Comment by Joe-Miccio** [comment]
I meet this error on my m1 mac:
`>>> import pyg_lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/pyg_lib/__init__.py", line 38, in <module>
    load_library('libpyg')
  File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/pyg_lib/__init__.py", line 35, in load_library
    torch.ops.load_library(spec.origin)
  File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/torch/_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/libpyg.so, 0x0006): Library not loaded: '/Users/runner/hostedtoolcache/Python/3.10.8/x64/lib/libpython3.10.dylib'
  Referenced from: '/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/libpyg.so'
  Reason: tried: '/Users/runner/hostedtoolcache/Python/3.10.8/x64/lib/libpython3.10.dylib' (no such file), '/usr/local/lib/libpython3.10.dylib' (no such file), '/usr/lib/libpython3.10.dylib' (no such file)
`
**my ENV INFO**:
`torch                     1.13.0                   pypi_0    pypi
torch-cluster             1.6.0                    pypi_0    pypi
torch-geometric           2.2.0                    pypi_0    pypi
torch-scatter             2.1.0                    pypi_0    pypi
torch-sparse              0.6.16                   pypi_0    pypi
torchaudio                0.13.0                   pypi_0    pypi
torchvision               0.14.0                   pypi_0    pypi
python                    3.10.9               h218abb5_2
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pyg-lib                   0.1.0+pt113              pypi_0    pypi
`

**Comment by Joe-Miccio** [comment]
> I meet this error on my m1 mac: `>>> import pyg_lib Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/pyg_lib/__init__.py", line 38, in <module> load_library('libpyg') File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/pyg_lib/__init__.py", line 35, in load_library torch.ops.load_library(spec.origin) File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/torch/_ops.py", line 573, in load_library ctypes.CDLL(path) File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/ctypes/__init__.py", line 374, in __init__ self._handle = _dlopen(self._name, mode) OSError: dlopen(/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/libpyg.so, 0x0006): Library not loaded: '/Users/runner/hostedtoolcache/Python/3.10.8/x64/lib/libpython3.10.dylib' Referenced from: '/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/libpyg.so' Reason: tried: '/Users/runner/hostedtoolcache/Python/3.10.8/x64/lib/libpython3.10.dylib' (no such file), '/usr/local/lib/libpython3.10.dylib' (no such file), '/usr/lib/libpython3.10.dylib' (no such file) ` **my ENV INFO**:
> 
> * torch                     1.13.0                   pypi_0    pypi
> * torch-cluster             1.6.0                    pypi_0    pypi
> * torch-geometric           2.2.0                    pypi_0    pypi
> * torch-scatter             2.1.0                    pypi_0    pypi
> * torch-sparse              0.6.16                   pypi_0    pypi
> * torchaudio                0.13.0                   pypi_0    pypi
> * torchvision               0.14.0                   pypi_0    pypi
> * python                    3.10.9               h218abb5_2
> * python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
> * python_abi                3.10                    2_cp310    conda-forge
> * pyg-lib                   0.1.0+pt113              pypi_0    pypi

i checked the install infomation and found that when i use `pip install pyg-lib -f https://data.pyg.org/whl/torch-1.13.0+cpu.html` to install pyg_lib, it shows :`Using cached https://data.pyg.org/whl/torch-1.13.0%2Bcpu/pyg_lib-0.1.0%2Bpt113-cp310-cp310-macosx_10_15_x86_64.whl (638 kB)`, it installed the x86_64 version, not the arm64 version.

**Comment by Joe-Miccio** [comment]
> 

reinstalled the python3.7:

- python                    3.7.16               h218abb5_0
- torch                     1.13.0                   pypi_0    pypi
- torch-cluster             1.6.0                    pypi_0    pypi
- torch-geometric           2.2.0                    pypi_0    pypi
- torch-scatter             2.1.0                    pypi_0    pypi
- torch-sparse              0.6.16                   pypi_0    pypi
- torch-spline-conv         1.2.1                    pypi_0    pypi
- torchaudio                0.13.0                   pypi_0    pypi
- torchvision               0.14.0                   pypi_0    py
- pyg-lib                   0.1.0+pt113              pypi_0    pypi

still have same error:
> import pyg_lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/anaconda3/envs/py37/lib/python3.7/site-packages/pyg_lib/__init__.py", line 38, in <module>
    load_library('libpyg')
  File "/opt/homebrew/anaconda3/envs/py37/lib/python3.7/site-packages/pyg_lib/__init__.py", line 35, in load_library
    torch.ops.load_library(spec.origin)
  File "/opt/homebrew/anaconda3/envs/py37/lib/python3.7/site-packages/torch/_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "/opt/homebrew/anaconda3/envs/py37/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/opt/homebrew/anaconda3/envs/py37/lib/python3.7/site-packages/libpyg.so, 0x0006): Library not loaded: '/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/Python'
  Referenced from: '/opt/homebrew/anaconda3/envs/py37/lib/python3.7/site-packages/libpyg.so'
  Reason: tried: '/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file)
>
 i installed pyg_lib by whell this time '[pyg_lib-0.1.0+pt113-cp37-cp37m-macosx_10_15_x86_64.whl](https://data.pyg.org/whl/torch-1.13.0%2Bcpu/pyg_lib-0.1.0%2Bpt113-cp37-cp37m-macosx_10_15_x86_64.whl)'

**Comment by rusty1s** [comment]
Yes, wheel support for M1 is not supported at the moment. You would need to install from source for `pyg-lib` on M1.

**Comment by semihcanturk** [comment]
Hmm, @Joe-Miccio 's error may not be limited to M1 Macs -- I'm also getting the same error, but on an Intel Mac. Any ideas?

> I meet this error on my m1 mac: `>>> import pyg_lib Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/pyg_lib/__init__.py", line 38, in <module> load_library('libpyg') File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/pyg_lib/__init__.py", line 35, in load_library torch.ops.load_library(spec.origin) File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/torch/_ops.py", line 573, in load_library ctypes.CDLL(path) File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/ctypes/__init__.py", line 374, in __init__ self._handle = _dlopen(self._name, mode) OSError: dlopen(/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/libpyg.so, 0x0006): Library not loaded: '/Users/runner/hostedtoolcache/Python/3.10.8/x64/lib/libpython3.10.dylib' Referenced from: '/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/libpyg.so' Reason: tried: '/Users/runner/hostedtoolcache/Python/3.10.8/x64/lib/libpython3.10.dylib' (no such file), '/usr/local/lib/libpython3.10.dylib' (no such file), '/usr/lib/libpython3.10.dylib' (no such file) ` **my ENV INFO**:
> 
> * torch                     1.13.0                   pypi_0    pypi
> * torch-cluster             1.6.0                    pypi_0    pypi
> * torch-geometric           2.2.0                    pypi_0    pypi
> * torch-scatter             2.1.0                    pypi_0    pypi
> * torch-sparse              0.6.16                   pypi_0    pypi
> * torchaudio                0.13.0                   pypi_0    pypi
> * torchvision               0.14.0                   pypi_0    pypi
> * python                    3.10.9               h218abb5_2
> * python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
> * python_abi                3.10                    2_cp310    conda-forge
> * pyg-lib                   0.1.0+pt113              pypi_0    pypi

**Comment by rusty1s** [comment]
Looks like your system cannot find your python env. Can you add it to `DYLD_LIBRARY_PATH`?

**Comment by Joe-Miccio** [comment]
> Hmm, @Joe-Miccio 's error may not be limited to M1 Macs -- I'm also getting the same error, but on an Intel Mac. Any ideas?
> 
> > I meet this error on my m1 mac: `>>> import pyg_lib Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/pyg_lib/__init__.py", line 38, in <module> load_library('libpyg') File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/pyg_lib/__init__.py", line 35, in load_library torch.ops.load_library(spec.origin) File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/torch/_ops.py", line 573, in load_library ctypes.CDLL(path) File "/opt/homebrew/anaconda3/envs/test/lib/python3.10/ctypes/__init__.py", line 374, in __init__ self._handle = _dlopen(self._name, mode) OSError: dlopen(/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/libpyg.so, 0x0006): Library not loaded: '/Users/runner/hostedtoolcache/Python/3.10.8/x64/lib/libpython3.10.dylib' Referenced from: '/opt/homebrew/anaconda3/envs/test/lib/python3.10/site-packages/libpyg.so' Reason: tried: '/Users/runner/hostedtoolcache/Python/3.10.8/x64/lib/libpython3.10.dylib' (no such file), '/usr/local/lib/libpython3.10.dylib' (no such file), '/usr/lib/libpython3.10.dylib' (no such file) ` **my ENV INFO**:
> > 
> > * torch                     1.13.0                   pypi_0    pypi
> > * torch-cluster             1.6.0                    pypi_0    pypi
> > * torch-geometric           2.2.0                    pypi_0    pypi
> > * torch-scatter             2.1.0                    pypi_0    pypi
> > * torch-sparse              0.6.16                   pypi_0    pypi
> > * torchaudio                0.13.0                   pypi_0    pypi
> > * torchvision               0.14.0                   pypi_0    pypi
> > * python                    3.10.9               h218abb5_2
> > * python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
> > * python_abi                3.10                    2_cp310    conda-forge
> > * pyg-lib                   0.1.0+pt113              pypi_0    pypi

I installed pyg by this https://github.com/rusty1s/pytorch_scatter/issues/241#issuecomment-1383939911, and its helpful.
The pyg_lib is installed by `pip install pyg-lib -f https://data.pyg.org/whl/nightly/torch-${TORCH}+${CUDA}.html`

pytorch version = 1.13.0, not sure whether different version is work. Maybe this can help you.

**Comment by ksmdnl** [comment]
> Yes, wheel support for M1 is not supported at the moment. You would need to install from source for `pyg-lib` on M1.
I tried installing it from source but it didn't work either.

`pip install git+https://github.com/pyg-team/pyg-lib.git
Collecting git+https://github.com/pyg-team/pyg-lib.git
  Cloning https://github.com/pyg-team/pyg-lib.git to /private/var/folders/bl/j35v6zps6yvgx5y0nwp4h7080000gn/T/pip-req-build-stsb4s67
  Running command git clone --filter=blob:none --quiet https://github.com/pyg-team/pyg-lib.git /private/var/folders/bl/j35v6zps6yvgx5y0nwp4h7080000gn/T/pip-req-build-stsb4s67
  Resolved https://github.com/pyg-team/pyg-lib.git to commit 029193467fe4ec61516e78859b7a8cfde3c40919
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyg-lib
  Building wheel for pyg-lib (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.0-arm64-cpython-310
      creating build/lib.macosx-11.0-arm64-cpython-310/pyg_lib
      copying pyg_lib/home.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib
      copying pyg_lib/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib
      copying pyg_lib/testing.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib
      copying pyg_lib/_triton.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib
      creating build/lib.macosx-11.0-arm64-cpython-310/pyg_lib/sampler
      copying pyg_lib/sampler/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib/sampler
      creating build/lib.macosx-11.0-arm64-cpython-310/pyg_lib/ops
      copying pyg_lib/ops/scatter_reduce.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib/ops
      copying pyg_lib/ops/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib/ops
      creating build/lib.macosx-11.0-arm64-cpython-310/pyg_lib/partition
      copying pyg_lib/partition/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib/partition
      running build_ext
      /private/var/folders/bl/j35v6zps6yvgx5y0nwp4h7080000gn/T/pip-req-build-stsb4s67/setup.py:77: UserWarning: Building times of 'pyg-lib' can be heavily improved by installing 'ninja': `pip install ninja`
        warnings.warn("Building times of 'pyg-lib' can be heavily improved"
      error: [Errno 2] No such file or directory: 'cmake'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyg-lib
  Running setup.py clean for pyg-lib
Failed to build pyg-lib
ERROR: Could not build wheels for pyg-lib, which is required to install pyproject.toml-based projects
`

**Comment by ksmdnl** [comment]
> > Yes, wheel support for M1 is not supported at the moment. You would need to install from source for `pyg-lib` on M1.
> 
> I tried installing it from source but it didn't work either.
> 
> ```
> pip install git+https://github.com/pyg-team/pyg-lib.git
> Collecting git+https://github.com/pyg-team/pyg-lib.git
>   Cloning https://github.com/pyg-team/pyg-lib.git to /private/var/folders/bl/j35v6zps6yvgx5y0nwp4h7080000gn/T/pip-req-build-stsb4s67
>   Running command git clone --filter=blob:none --quiet https://github.com/pyg-team/pyg-lib.git /private/var/folders/bl/j35v6zps6yvgx5y0nwp4h7080000gn/T/pip-req-build-stsb4s67
>   Resolved https://github.com/pyg-team/pyg-lib.git to commit 029193467fe4ec61516e78859b7a8cfde3c40919
>   Running command git submodule update --init --recursive -q
>   Preparing metadata (setup.py) ... done
> Building wheels for collected packages: pyg-lib
>   Building wheel for pyg-lib (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [21 lines of output]
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build/lib.macosx-11.0-arm64-cpython-310
>       creating build/lib.macosx-11.0-arm64-cpython-310/pyg_lib
>       copying pyg_lib/home.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib
>       copying pyg_lib/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib
>       copying pyg_lib/testing.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib
>       copying pyg_lib/_triton.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib
>       creating build/lib.macosx-11.0-arm64-cpython-310/pyg_lib/sampler
>       copying pyg_lib/sampler/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib/sampler
>       creating build/lib.macosx-11.0-arm64-cpython-310/pyg_lib/ops
>       copying pyg_lib/ops/scatter_reduce.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib/ops
>       copying pyg_lib/ops/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib/ops
>       creating build/lib.macosx-11.0-arm64-cpython-310/pyg_lib/partition
>       copying pyg_lib/partition/__init__.py -> build/lib.macosx-11.0-arm64-cpython-310/pyg_lib/partition
>       running build_ext
>       /private/var/folders/bl/j35v6zps6yvgx5y0nwp4h7080000gn/T/pip-req-build-stsb4s67/setup.py:77: UserWarning: Building times of 'pyg-lib' can be heavily improved by installing 'ninja': `pip install ninja`
>         warnings.warn("Building times of 'pyg-lib' can be heavily improved"
>       error: [Errno 2] No such file or directory: 'cmake'
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for pyg-lib
>   Running setup.py clean for pyg-lib
> Failed to build pyg-lib
> ERROR: Could not build wheels for pyg-lib, which is required to install pyproject.toml-based projects```
> ```

Installing rdkit seems to solve the issue somehow.

**Comment by rusty1s** [comment]
Yes, you need `cmake` for installation.

**Comment by businessabstraction** [comment]
> Yeah, that's because we don't yet provide pre-built M1 wheels, and `pyg-lib` is not yet on PyPi. You can try to run via
> 
> ```
> pip install git+https://github.com/pyg-team/pyg-lib.git
> ```

trying to install pyg-lib in all ways I found. When following your instructions, get
```
      running build_ext
      error: [Errno 2] No such file or directory: 'cmake'
```

**Comment by vexogon** [comment]
this works!

> > Looks like your system cannot find your python env. Can you add it to `DYLD_LIBRARY_PATH`?
> 
> This is due to pip's build isolation (["A build frontend SHOULD, by default, create an isolated environment for each build, containing only the standard library and any explicitly requested build-dependencies."](https://peps.python.org/pep-0517/#recommendations-for-build-frontends-non-normative:~:text=A%20build%20frontend%20SHOULD%2C%20by%20default%2C%20create%20an%20isolated%20environment%20for%20each%20build%2C%20containing%20only%20the%20standard%20library%20and%20any%20explicitly%20requested%20build%2Ddependencies.)). There is an `import torch` in build_ext but it isn't listed as a requirement in pyproject.toml (for good reason). Bypass this with:
> 
> `pip install --no-build-isolation git+https://github.com/pyg-team/pyg-lib.git`
