### ISSUE TITLE
PyPi requirements failed on MacOS

### ISSUE THREAD

**Issue by ChocolateDave** [pyg-team/pyg-lib#221]
### 😵 Describe the installation problem

Hello there,

I was trying to create a `requirements.txt` file for environment configurations on my 2023 Mac Mini, but I got the following error when I ran `pip install -e .`:

```text
Looking in links: https://data.pyg.org/whl/torch-1.12.0+cpu
ERROR: Could not find a version that satisfies the requirement pyg_lib (from versions: none)
ERROR: No matching distribution found for pyg_lib
```

However, the same scripts work well with an Intel chip on my 2015 Macbook Pro. I attached part of  the requirements file related to this issue below for your reference:

```yaml
# =========== pytorch-geometric ===========
# For Linux
--find-links https://data.pyg.org/whl/torch-1.12.0+cu116.html
torch_geometric==2.3.0;    platform_system == "Linux"
pyg_lib==0.2.0;            platform_system == "Linux"
torch_cluster==1.6.0;      platform_system == "Linux"
torch_scatter==2.1.0;      platform_system == "Linux"
torch_sparse==0.6.16;      platform_system == "Linux"
torch_spline_conv==1.2.1;  platform_system == "Linux"

# For Mac
--find-links https://data.pyg.org/whl/torch-1.12.0+cpu.html
torch_geometric==2.3.0;    platform_system == "Darwin"
pyg_lib==0.2.0;            platform_system == "Darwin"
torch_cluster==1.6.0;      platform_system == "Darwin"
torch_scatter==2.1.0;      platform_system == "Darwin"
torch_sparse==0.6.16;      platform_system == "Darwin"
torch_spline_conv==1.2.1;  platform_system == "Darwin"
```

### Environment

* `pyg-lib` version: `0.2.0`
* PyTorch version: `1.12.0`
* OS: `Mac OS Ventura 13.2.1`
* Python version: Python `3.9`
* CUDA/cuDNN version: `cpu`
* How you installed PyTorch and `pyg-lib` (`conda`, `pip`, source): `pip`
* Any other relevant information: see above.

**Comment by rusty1s** [comment]
We currently do not provide M1/M2 wheels for macOS, so the only workaround is to currently compile them from source, sorry about this. Please note that these dependencies are also optional to run PyG 2.3, so safe yourself some time and only install the ones you desperately need.

**Comment by ChocolateDave** [comment]
> We currently do not provide M1/M2 wheels for macOS, so the only workaround is to currently compile them from source, sorry about this. Please note that these dependencies are also optional to run PyG 2.3, so safe yourself some time and only install the ones you desperately need.

Thank you for the prompt reply. I'll look into how to build them from source.
