### ISSUE TITLE
pyg_lib wheels missing from https://data.pyg.org/whl/torch-2.2.0%2Bcpu.html

### ISSUE THREAD

**Issue by jpata** [pyg-team/pyg-lib#296]
### 😵 Describe the installation problem

pyg-lib is missing from https://data.pyg.org/whl/torch-2.2.0%2Bcpu.html, so pip installing pyg_lib following the [instructions](https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html) fails:
```
Run pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv torch_geometric -f https://data.pyg.org/whl/torch-2.2.0+cpu.html
Looking in links: https://data.pyg.org/whl/torch-2.2.0+cpu.html
ERROR: Could not find a version that satisfies the requirement pyg_lib (from versions: none)
ERROR: No matching distribution found for pyg_lib
```

### Environment

* PyTorch version: 2.2.0
* OS: Linux
* Python version: 3.10
* CUDA/cuDNN version: CPU
* How you installed PyTorch and `pyg-lib` (`conda`, `pip`, source): `pip`

**Comment by rusty1s** [comment]
You currently have to use the nightly wheels for PyTorch 2.2 support. The README is a bit ahead of time since we will release a new `pyg-lib` version tomorrow :)

**Comment by jpata** [comment]
Thanks, I see it works now!
