### ISSUE TITLE
Issue iterating with `NeighborLoader` on pyg-lib 0.4.0

### ISSUE THREAD

**Issue by adachille** [pyg-team/pyg-lib#299]
### 🐛 Describe the bug

Hey PyG team :wave: I'm getting an error when trying to iterate with a `NeighborLoader`. I started getting this a couple of days ago, coinciding with the release of pyg-lib 0.4.0. I tested with pyg-lib 0.3.1, and the issue went away.

You should be able to reproduce the bug with the following code from the docs:
```python
import os

!pip install torch==2.2.*
import torch
os.environ['CUDA'] = torch.version.cuda.replace(".", "")

!pip install --upgrade torch-geometric
!pip install --upgrade pyg-lib -f https://data.pyg.org/whl/torch-2.2.0+cu${CUDA}.html
!pip install --upgrade torch-sparse -f https://data.pyg.org/whl/torch-2.2.0+cu${CUDA}.html

from torch_geometric.datasets import Planetoid
from torch_geometric.loader import NeighborLoader

data = Planetoid(".", name='Cora')[0]

loader = NeighborLoader(
    data,
    # Sample 30 neighbors for each node for 2 iterations
    num_neighbors=[30] * 2,
    # Use a batch size of 128 for sampling training nodes
    batch_size=128,
    input_nodes=data.train_mask,
)

sampled_data = next(iter(loader))
print(sampled_data.batch_size)
```

### Environment

* `pyg-lib` version: 0.4.0
* PyTorch version: 2.2.0
* OS: Linux
* Python version: 3.9
* CUDA/cuDNN version: 12.1
* How you installed PyTorch and `pyg-lib` (`conda`, `pip`, source): _Reference code sample_
* Any other relevant information:

**Comment by rusty1s** [comment]
Yes, sorry. We released `pyg-lib` a bit too early. Please stay on `pyg-lib==0.3.1` for PyG 2.4, or use PyG master (or upcoming 2.5 version later) for `pyg-lib==0.4.0`.

**Comment by adachille** [comment]
No worries, thanks for all your work on this! Should I close this out then?

**Comment by rusty1s** [comment]
Yes, we can close. Thank you.
