### ISSUE TITLE
Error while using `LinkLoaderNeighbor` on Windows

### ISSUE THREAD

**Issue by ishanki19-pixel** [pyg-team/pyg-lib#311]
### 🐛 Describe the bug

I am attaching the Image of the bug:
![Screenshot (513)](https://github.com/pyg-team/pyg-lib/assets/81527206/2be1e676-5d70-49b9-92a8-d5764f4b3147)

### Environment

* `pyg-lib` version:
* PyTorch version: 2.2.1+cu121
* OS: Windows
* Python version:3.10.12
* CUDA/cuDNN version: CPU
* How you installed PyTorch and `pyg-lib` (`conda`, `pip`, source): pip (Note: there was also issue which is currently already opened by someone regarding the setup.py file)
* Any other relevant information:

**Comment by rusty1s** [comment]
Have you considered to simply upgrade `pyg-lib` (as the error suggests)?

**Comment by ishanki19-pixel** [comment]
I am again and again getting error regarding the build failing, I have many different ways still build is getting failed for pyg-lib.
![Uploading Screenshot (519).png…]()

**Comment by ishanki19-pixel** [comment]
Actually, I have just gone through the repo of pyg-lib where I found that they have informed themselves that currently window wheels are not working and they are working over that!!!
I hope this issue might get resolved asap!

**Comment by rusty1s** [comment]
I see. I missed the part that you are working on Windows. What does
```
pip install ninja wheel cmake
pip install --verbose git+https://github.com/pyg-team/pyg-lib.git
```
return in your case?

**Comment by ishanki19-pixel** [comment]
It returns the same error as told before!
I hope the team would come up with a solution asap!

**Comment by rusty1s** [comment]
I was referring to the installation log, not the error you see when you wanna use edge-level temporal sampling.

**Comment by ishanki19-pixel** [comment]
Yeah, I was too referring to the installation itself! but there is problem with the wheels and setup.py file.

**Comment by rusty1s** [comment]
Can you post the installation log here when running
```
pip install ninja wheel cmake
pip uninstall pyg-lib
pip uninstall pyg-lib
pip install --verbose git+https://github.com/pyg-team/pyg-lib.git

**Comment by ishanki19-pixel** [comment]
After running the above code,
I got this output:
![Screenshot (519)](https://github.com/pyg-team/pyg-lib/assets/81527206/e6a29ace-b21b-4a13-8a31-6d19683ec922)
![Screenshot (520)](https://github.com/pyg-team/pyg-lib/assets/81527206/e9516cc0-db37-4397-aa28-cc77b2dcbce3)
![Screenshot (521)](https://github.com/pyg-team/pyg-lib/assets/81527206/c55b529d-a38b-493a-bbd4-0024c7339971)
![Screenshot (522)](https://github.com/pyg-team/pyg-lib/assets/81527206/ddac2979-503b-4006-84fc-fae65a2273aa)
![Screenshot (523)](https://github.com/pyg-team/pyg-lib/assets/81527206/93630736-48dd-4ed3-a20b-d6ddedcebe63)
![Screenshot (524)](https://github.com/pyg-team/pyg-lib/assets/81527206/e906d1d5-98a4-414d-aa2d-133b187fccf4)

**Comment by rusty1s** [comment]
Got it, can you try to install via
```
FORCE_CUDA=0 pip install --verbose git+https://github.com/pyg-team/pyg-lib.git

**Comment by ishanki19-pixel** [comment]
Getting the same errors:
![Screenshot (525)](https://github.com/pyg-team/pyg-lib/assets/81527206/784dba94-1488-409d-bcc2-d6304e9f460f)
![Screenshot (526)](https://github.com/pyg-team/pyg-lib/assets/81527206/a8d54d87-f4cb-4ca4-8d13-0be40eaa9659)
![Screenshot (527)](https://github.com/pyg-team/pyg-lib/assets/81527206/78740d75-d879-415e-ba5b-f016f39a161e)
![Screenshot (528)](https://github.com/pyg-team/pyg-lib/assets/81527206/909965ee-7ec7-4e42-b038-0efa86d4f4d3)
![Screenshot (529)](https://github.com/pyg-team/pyg-lib/assets/81527206/aaa56c93-bd6d-4892-ad13-cb537cd1de7e)

**Comment by rusty1s** [comment]
That's very strange. It still tries to build CUDA although `FORCE_CUDA=0` (seems Windows related). Can you download the repo locally, change [this line](https://github.com/pyg-team/pyg-lib/blob/master/setup.py#L61) to
```python
            '-DWITH_CUDA=OFF',
```
and try again?

**Comment by ishanki19-pixel** [comment]
Its not working again, showing the same error even if I tried it running through my cmd.

**Comment by rusty1s** [comment]
Okay, I can try to find some time to enable Windows builds, but it may take some time. You can also try to install `torch-sparse` if `pyg-lib` causes issues.

**Comment by ishanki19-pixel** [comment]
Okay but pls try to fix this asap.

**Comment by rusty1s** [comment]
`pyg-lib` nows supports Windows, and you can install it from nightly:
```
pip install pyg-lib -f https://data.pyg.org/whl/nightly/torch-${TORCH}+${CUDA}.html
```
by replacing `${TORCH}` and `${CUDA}` according to your installation.

**Comment by iishutov** [comment]
> `pyg-lib` nows supports Windows, and you can install it from nightly:
> 
> ```
> pip install pyg-lib -f https://data.pyg.org/whl/nightly/torch-${TORCH}+${CUDA}.html
> ```
> 
> by replacing `${TORCH}` and `${CUDA}` according to your installation.

Thanks, @rusty1s, it works as it should be!

**Comment by ishanki19-pixel** [comment]
yes @rusty1s thank you so much, its working now!!!!
